
/**
 * Author:  juangu
 * Created: 16-feb-2017
 */

-- COMO ROOT PARA CREAR LA BBDD Y EL USUARIO

-- Mostrar los CHARSETs instalados:
SHOW CHARACTER SET;
-- Mostrar COLLATIONS instalados:
SHOW COLLATION;
-- CREAMOS LA BBDD PARA UTF-8 COLLATION EN ESPAÑOL
CREATE DATABASE gestion_academica  
	CHARACTER SET utf8 COLLATE utf8_spanish_ci;


-- CREAMOS EL USUARIO 
DROP USER damuser23;
CREATE USER damuser23 IDENTIFIED BY 'damuser';

-- DAMOS PERMISOS EN LA BBDD PARA EL NUEVO USUARIO
grant all privileges on gestion_academica.* to 'damuser23'@'%' identified by 'damuser';
grant all privileges on gestion_academica.* to 'damuser23'@'localhost' identified by 'damuser';
flush privileges;


-- COMO USUARIO PARA CREAR LAS TABLAS Y POBLAR DE DATOS


DROP TABLE IF EXISTS ALUM_ASIG;
DROP TABLE IF EXISTS PROF_ASIG;
DROP TABLE IF EXISTS ALUMNO;
DROP TABLE IF EXISTS PROFESOR;
DROP TABLE IF EXISTS ASIGNATURA;

CREATE TABLE ALUMNO (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	apellido VARCHAR(50) NOT NULL ) ;

CREATE TABLE PROFESOR (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	apellido VARCHAR(50) NOT NULL );

CREATE TABLE ASIGNATURA (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(25) NOT NULL ,
	curso SMALLINT,
	ciclo VARCHAR(50));

CREATE TABLE ALUM_ASIG (
	ASIGNATURA INT,
	ALUMNO INT,
    FALTAS INT,
	PRIMARY KEY(ASIGNATURA,ALUMNO),
	FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(id) ,
	FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURA(id) );

CREATE TABLE PROF_ASIG (
	ASIGNATURA INT,
	PROFESOR INT,
    HORAS_SEMANALES INT,
	PRIMARY KEY(ASIGNATURA, PROFESOR),
	FOREIGN KEY (PROFESOR) REFERENCES PROFESOR(id),
	FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURA(id));

INSERT INTO ALUMNO VALUES (
	NULL,
	'PEPE',
	'PEREZ');
INSERT INTO PROFESOR VALUES (
	NULL,
	'JUAN',
	'GUTIERREZ');
INSERT INTO ASIGNATURA VALUES (
	NULL,
	'Acceso a Datos',
	2,
	'DAM'
);

-- INSERT INTO PROF_ASIG VALUES ();
-- INSERT INTO PROF_ASIG VALUES ();
